---
- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    #image_id: "ami-026ebd4cfe2c043b2"  # Redhat
    image_id: "ami-0c101f26f147fa7fd"  # Amazon Linux
    key_name: "master-danapayer"
    #security_group: "sg-08c1516cca7db10b9"
    security_group: "launch-wizard-4"
    subnet_id: "subnet-0645fbb28946b6a62"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        #count: 1
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        key_name: "{{ key_name }}"
        security_group: "{{ security_group }}"
        vpc_subnet_id: "{{ subnet_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        tags:
          Name: "Ansible_Instance"
      register: ec2_info

